//
//  AgeVerifier.swift
//  Tailor Your Tales
//
//  Created by Daniel Koronthaly on 5/6/24.
//

import SwiftUI

struct AgeVerifier: View {
    
    @Environment(\.presentationMode) var presentationMode
    
    struct Question {
        var text: String
        var answers: [String]
        var correctAnswerIndex: Int
    }
    
    let questions: [Question] = [
        Question(
            text: "What is the capital of France?",
            answers: ["Paris", "London", "Rome", "Berlin"],
            correctAnswerIndex: 0
        ),
        Question(
            text: "What is the largest planet in our solar system?",
            answers: ["Earth", "Jupiter", "Mars", "Saturn"],
            correctAnswerIndex: 1
        ),
        Question(
            text: "What is the chemical symbol for water?",
            answers: ["H2O", "CO2", "O2", "NaCl"],
            correctAnswerIndex: 0
        ),
        Question(
            text: "Who painted the Mona Lisa?",
            answers: ["Pablo Picasso", "Leonardo da Vinci", "Vincent van Gogh", "Michelangelo"],
            correctAnswerIndex: 1
        ),
    ]
    
    @State private var randomIndex = Int.random(in: 0..<4)
    @State private var shouldNavigateToStoryList = false
    
    var body: some View {
        let question = questions[randomIndex]
        
        VStack {
            Spacer()
            //Hide autogenerated back button
                .navigationBarBackButtonHidden(true)
            //Replace with larger red back button
            //.toolbar(content: {
               // ToolbarItem (placement: .topBarLeading)  {
                    
                    Button(action: {presentationMode.wrappedValue.dismiss()}, label: {
                        Text("Back").font(.custom("Helvetica Bold", size: 35))
                            .frame(width: 150, height: 100)
                            .background(Color(red: 0.5804, green: 0.0863, blue: 0))
                            .foregroundColor(.white)
                            .cornerRadius(10)
                            //.padding(.top, 50)
                            .padding(.trailing, UIScreen.main.bounds.size.width * 1.5 / 2)
                    })
                    //.padding(.top, 15)
                    
                    
                //}
           // })
            //Child instructions
            Text("This area is for adults only! If you are a child, click the red square to go back.")
                .font(.custom("Helvetica Bold", size: 35))
                .minimumScaleFactor(0.75)
                .padding()
                .foregroundColor(Color(red: 0.5804, green: 0.0863, blue: 0))
            Spacer()
            
            Divider()
            //Question
            Text("Select the correct answer to proceed: " + question.text).font(.custom("Helvetica Bold", size: 35))
                .minimumScaleFactor(0.75)
                .padding()
            
            // Buttons in a 2x2 grid
            VStack(spacing: 0) {
                ForEach(0..<4) { index in
                    Button(action: {
                        if index == question.correctAnswerIndex {
                            // Navigate to StoryList if correct answer is selected
                            shouldNavigateToStoryList = true
                        } else {
                            // Go back if wrong answer is selected
                            presentationMode.wrappedValue.dismiss()
                        }
                    }) {
                        Text(question.answers[index])
                            .font(.custom("Helvetica Bold", size: 30))
                            .frame(width: 300, height: 100)
                            .background(Color(red: 0, green: 0.2667, blue: 0.7020))
                            .foregroundColor(.white)
                            .cornerRadius(10)
                    }
                    .padding()
                }
            }
            .navigationDestination(isPresented: $shouldNavigateToStoryList) {
                StoryListAdult()
            }
        }
    }
}

#Preview {
    AgeVerifier()
}
